name: Docs

on:
  push:
    branches:
      - trunk
  workflow_dispatch:

# Allow the GITHUB_TOKEN to deploy to GitHub Pages.
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment, without cancelling an in-progress one.
concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    name: Build MkDocs site
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - uses: actions/setup-python@v7
        with:
          python-version: "3.12"

      - name: Setup uv (Rust)
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install Python with uv
        run: uv python install 3.12

      - run: echo "cache_id=$(date --utc '+%V')" >> "$GITHUB_ENV"

      - uses: actions/cache@v6
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: ~/.cache
          restore-keys: |
            mkdocs-material-

      - name: Install dependencies
        run: uv sync --dev

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Build site
        run: uv run mkdocs build --strict

      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    name: Deploy to GitHub Pages
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4
